### ISSUE TITLE
Problem starting bot

### ISSUE THREAD

**Issue by gamer50082** [Yankue/yankuesmusicbot#2]
![6E6D4C4C-707E-4A02-94A0-31C476D30F3B](https://user-images.githubusercontent.com/73380763/128181593-b73b0520-a36c-44b5-a8f7-41bc1b2e24d4.jpeg)

**Comment by Yankue** [comment]
I know soundcloud has been causing some problems especially since you can no longer get API keys from them. I think it'll be completely removed very soon, for now you can just uninstall the module and remove all mentions of it and it should work

**Comment by gamer50082** [comment]
Still does not work

**Comment by gamer50082** [comment]
![IMG_2051](https://user-images.githubusercontent.com/73380763/128853566-4a683d28-81f1-4136-b638-668436f4fdec.jpeg)

**Comment by Yankue** [comment]
I said completely remove all bits about soundcloud

**Comment by gamer50082** [comment]
How to remove all I don’t know where it is

**Comment by SinisterDeveloper** [comment]
- [ ] Uninstall Soundcloud by running `npm uninstall soundcloud-downloader`
- [ ] Remove the code where Soundcloud package has been used, I think the `commands/play.js`, `commands/playlist.js` and `include/play.js` has it.
- [ ] Run the bot

**Comment by Yankue** [comment]
@gamer50082 I have released a 1-time update that removes soundcloud from everywhere, and also fixes some bugs often seen with ytdl. If you pull it now and run it it should work.
